name: Report to Telegram
on:
    workflow_call:    
    workflow_dispatch:
        

jobs:
    report:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-java@v3
            with:
              distribution: "zulu"
              java-version: "17"
              
          - name: report
            env:
             TG_TOKEN: ${{ secrets.TG_TOK }}
             RELNOT: '${{ vars.RELEASE_NOTE }}'
            if: env.TG_TOKEN != null
            run: |
                echo "${{env.RELNOT}}"
                TG_CHAT="@rev_m8tr"
                MSG="${{env.RELNOT}}"
                POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
                curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "disable_web_page_preview=true" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
